# Variazione del programma precedente

# COMPLETA IL CODICE DOVE TROVI ________ !
# QUANDO CI SONO I COMMENTI IN MAIUSCOLO SIGINIFCA CHE DEVI SCRIVERE TU
# IL CODICE IN BASE A QUANTO RICHIESTO NEL COMMENTO

""" SCOPO: Uniamo tre stringhe in una nuova stringa.
Le tre stringhe vengono richieste all'utente"""

# CHIEDIAMO ALL'UTENTE DI INSERIRE IL NOME DI UNA MATERIA SCOLASTICA

# CHIEDIAMO ALL'UTENTE DI INSERIRE IL NOME DI UN PROFESSORE

# CHIEDIAMO ALL'UTENTE DI INSERIRE UN'AULA

# UNIAMO LE STRINGHE IN UNA NUOVA STRINGA CHIAMATA 'orario'

# STAMPA IL RISULTATO
