# Variazione del programma precedente

# COMPLETA IL CODICE DOVE TROVI ________ !
# QUANDO CI SONO I COMMENTI IN MAIUSCOLO SIGINIFCA CHE DEVI SCRIVERE TU 
# IL CODICE IN BASE A QUANTO RICHIESTO NEL COMMENTO

""" SCOPO: Uniamo due stringhe in una nuova stringa. 
Le due stringhe vengono richieste all'utente"""

# CHIEDIAMO ALL'UTENTE DI INSERIRE LA PRIMA STRINGA

# CHIEDIAMO ALL'UTENTE DI INSERIRE LA SECONDA STRINGA

# CHIEDIAMO ALL'UTENTE DI INSERIRE LA TERZA STRINGA

# UNIAMO LE STRINGHE IN UNA NUOVA STRINGA

# STAMPA IL RISULTATO 